
# extract RGB frames
extract_rgb: true
# extract anonymization masks
extract_masks: true
# extract depth frames
extract_depth: true

# folder where the data is downloaded
data_root: /data1/home/lucky/ELSED/dataset

# scene_ids: [c173f62b15]
scene_ids: [69e5939669]