# release data downloaded to disk
data_root: /data1/home/lucky/ELSED/dataset
# c173f62b15
scene_list: [69e5939669]
filter_scenes: [69e5939669]

# image type - iphone or dslr
image_type: iphone

no_log: true

# subsample images 
subsample_factor: 1
# downsample images and rasterize
image_downsample_factor: null

rasterout_dir: /data1/home/lucky/ELSED/dataset/raster_iphone

limit_images: None

wandb_group: null
wandb_notes: null

batch_size: 5
limit_batches: null
skip_existing: true