name: superpoint-gpu
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8          # CUDA 11.8 runtime
  - cudnn=8.9                 # 只写主版本号
  - numpy
  - scipy
  - tqdm
  - pyyaml
  - flake8
  - jupyter
  - pip
  - pip:
      - tensorflow==2.15.0
      - opencv-python
      - opencv-contrib-python
